# For local development _excluding_ the test pages, use the option
# --config _config.yml,_config_dev.yml
# See https://stackoverflow.com/a/27400343

url: http://localhost:4000/

# For local development including the test pages, use the option
# --config _config.yml,_config_dev.yml,_config_test.yml
